server:
  port: 9090

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
  flyway:
    enabled: false
  docker:
    compose:
      enabled: false

# Mock은 내보내지 않음
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
